### ISSUE TITLE
Feature: MySQL Warning System ( Codename: MWS )

### ISSUE THREAD

**Issue by ApertureDevelopment** [Aperture-Development/MSync-2#81]
### Description

A MySQL based warning system to support infractions across multible servers. 

### To-Do
What to do in the order it will be done

# Basic
- [ ] Table structure
- [ ] Warning logic
- [ ] Testing

# Table Structure
- [ ] Warning table
- [ ] Infractions table
- [ ] Punishment table

# Warning logic
- [ ] Warn user
- [ ] Punishments
- [ ] GUI
- [ ] Active Infraction detection
- [ ] Automatic cooldown
- [ ] Hooks

# Testing

- [ ] Warn user
- [ ] Infractions cause punishment
- [ ] Punishments are not being executed twice
- [ ] Warns are not being reduced when a punishment is executed
- [ ] Client is able to see their own warns
- [ ] Admin can see all warns of other users and in total

**Comment by ApertureDevelopment** [comment]
After careful consideration, I think this would be out of scope for MSync. This may become a stand-alone product, but not part of MSync
